using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(fileName = "LevelConfig", menuName = "Level/Level Config", order = 1)]
public class LevelConfig : ScriptableObject
{
    [Header("Grid Dimensions")]
    [Range(2, 10)] public int Rows = 8;
    [Range(2, 10)] public int Columns = 8;

    [Header("Selected Colors")]
    public List<BlockColorData> AvailableColors = new List<BlockColorData>();

    [Header("Group Icon Thresholds")]
    [Tooltip("Minimum blocks for First icon (A)")]
    [Range(2, 20)] public int ThresholdA = 4;

    [Tooltip("Minimum blocks for Second icon (B)")]
    [Range(2, 20)] public int ThresholdB = 7;

    [Tooltip("Minimum blocks for Third icon (C)")]
    [Range(2, 20)] public int ThresholdC = 9;

    [Header("Grid Visual Settings")]
    [Tooltip("Size of each cell (block size)")]
    [Range(0.5f, 3f)] public float CellSize = 1f;
    [Tooltip("Spacing between cells (gap/padding)")]
    [Range(0f, 0.5f)] public float CellPadding = 0.1f;

    [Header("Performance Settings")]
    public int ObjectPoolSize = 100;
    public float BlockFallSpeed = 10f;
    public float BlastDelay = 0.2f;
    public float BlockSpacing = 1f;

    [Header("Initial Grid Data (Generated by Tool)")]
    [HideInInspector] public int[] InitialGridData;

    public float TotalCellSpacing => CellSize + CellPadding;

    // Runtime helpers
    public int ColorCount => AvailableColors.Count;

    public void InitializeGridData()
    {
        if (InitialGridData == null || InitialGridData.Length != Rows * Columns)
        {
            InitialGridData = new int[Rows * Columns];
            RandomizeGrid();
        }
    }

    public void RandomizeGrid()
    {
        if (AvailableColors.Count == 0)
        {
            Debug.LogWarning("No colors available! Add BlockColorData to AvailableColors list.");
            return;
        }

        for (int i = 0; i < InitialGridData.Length; i++)
        {
            int randomColorIndex = Random.Range(0, AvailableColors.Count);
            InitialGridData[i] = AvailableColors[randomColorIndex].ColorID;
        }
    }

    public int GetColorIDAt(int x, int y)
    {
        if (x < 0 || x >= Columns || y < 0 || y >= Rows)
            return -1;
        return InitialGridData[y * Columns + x];
    }

    public void SetColorIDAt(int x, int y, int colorID)
    {
        if (x < 0 || x >= Columns || y < 0 || y >= Rows)
            return;
        InitialGridData[y * Columns + x] = colorID;
    }

    public BlockColorData GetColorData(int colorID)
    {
        return AvailableColors.Find(c => c.ColorID == colorID);
    }

    public BlockColorData GetRandomColorData()
    {
        if (AvailableColors.Count == 0)
            return null;
        return AvailableColors[Random.Range(0, AvailableColors.Count)];
    }

    public BlockIconType GetIconType(int groupSize)
    {
        if (groupSize > ThresholdC) return BlockIconType.Third;
        if (groupSize > ThresholdB) return BlockIconType.Second;
        if (groupSize > ThresholdA) return BlockIconType.First;
        return BlockIconType.Default;
    }

    public bool IsColorAvailable(int colorID)
    {
        return AvailableColors.Exists(c => c.ColorID == colorID);
    }
}
